### PR TITLE
Fixed Bruteforce Bug #224

### LINKED ISSUE #224: Bruteforce Bug
**Describe the bug**
> Please provide a clear and concise description of what the bug is.
If you bruteforce a PC and then the pc has been shut down while you bruteforced him, there is no terminal output.

**Reproduce**
> Steps to reproduce the behavior.
Hack a PC while he is offline, but he has to be online at the start

**Logs**
> Please provide your logs and/or screenshots of the problem.
no ;D

### PR DESCRIPTION
**Pull request by Tert0**
**Description**
Shows an "Error" in the Terminal when you type stop an the Target Device/Service is not Online.
**Issue**
Closes #224 

**Testing Instructions**
- Start 2 Computers
- Start bruteforcing Computer 2
- Shutdown Computer 2
- Type in stop to the Bruteforce Interface
- You should see the "Error"

### CODE REVIEW

File: src/app/desktop/windows/terminal/terminal-states.ts [hunk 1]
```diff
@@ -1059,6 +1059,10 @@ export class DefaultTerminalState extends CommandTerminalState {
             if (differentServiceAttacked) {
               startAttack();
             }
+          }, (err) => {
+              if (err.message === 'service_not_running') {
+                this.terminal.outputText('This Computer or Service is not Online.');
```
Comment (JannikEmmerich) [inline src/app/desktop/windows/terminal/terminal-states.ts:1064]: I would probably change the error message to the following:
```suggestion
                this.terminal.outputText('Target service is unreachable.');
```

**Review by JannikEmmerich — APPROVED** [review]

**Review by MarcelCoding — APPROVED** [review]
